Update Tue Jan 31 22:53:31 EST 2023

diff --git a/scripts/pull-updates b/scripts/pull-updates
--- a/scripts/pull-updates
+++ b/scripts/pull-updates
@@ -1,16 +1,22 @@
 HC=$(git rev-parse HEAD)
-git stash -u
-git pull
-if ! git stash pop
-then
-  git reset --hard $HC
-  git stash pop
-  echo ""
-  echo "We cannot get the latest changes to the class materials, because you have local changes that conflict with them."
-  echo "The conflicting files should be visible in the trace message above, after the word CONFLICT."
-  echo "To erase your local changes, run the command `reset-all`."
-  echo "(Warning: this cannot be undone.)"
-  echo "Remember that you should only be modifying files in your personal working directories."
-else 
+if [[ $(git stash push -m "push-update" -u) == *"No local changes to save"* ]]
+then 
+  git pull 
   lake exe cache get
+else 
+  git pull 
+  if ! git stash apply stash^{/push-update}
+  then
+    git reset --hard $HC
+    git stash apply stash^{/push-update}
+    git stash drop
+    echo ""
+    echo "We cannot get the latest changes to the class materials, because you have local changes that conflict with them."
+    echo "The conflicting files should be visible in the trace message above, after the word CONFLICT."
+    echo "To erase your local changes, run the command `reset-all`."
+    echo "(Warning: this cannot be undone.)"
+  else 
+    git stash drop
+    lake exe cache get
+  fi
 fi
